repos:
  # Black - Formatação automática de código
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use a versão mais recente disponível
    hooks:
      - id: black

  # Flake8 - Verificação de linting e padrões de código
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0  # Use a versão mais recente disponível
  #   hooks:
  #     - id: flake8
  #       args:
  #         - --max-line-length=88
  #         - --ignore=E203,W503  # Ignorar padrões específicos

  # isort - Ordenação de imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use a versão mais recente disponível
    hooks:
      - id: isort
        args:
          - --profile=black

  # Verificação de arquivos grandes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files

  # Verificação de final de linha (evitar erros de EOL)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer

  # Verificação de arquivos JSON válidos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json

  # Verificação de arquivos YAML válidos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml

  -   repo: local
      hooks:
        - id: run-tests
          name: Run Pytest tests
          entry: pytest  # Comando para rodar os testes
          language: system  # Usamos 'system' porque estamos chamando pytest como comando do sistema
          types: [python]
