name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=88 --ignore=E203,W503

    - name: Format with black
      run: |
        black --check .

    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings
      
    - name: Security audit
      run: |
        pip-audit
    - name: Run tests with coverage
      run: |
        pytest --cov=seu_pacote tests/
